### ISSUE TITLE
Is the current setup building both x86 and arm? How would you build for a specific architecture?

### ISSUE THREAD

**Issue by bwang29** [dougdiego/CrosswalkDemo#2]

**Comment by dougdiego** [comment]
Gradle/Maven downloads this file:
https://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/xwalk/xwalk_core_library/10.39.235.15/xwalk_core_library-10.39.235.15.aar

It contains libraries for both: armeabi-v7a and x86

<img width="563" alt="screen shot 2015-08-04 at 5 28 22 am" src="https://cloud.githubusercontent.com/assets/3278390/9060563/e8057094-3a69-11e5-84c4-2c84000bd797.png">

**Comment by bwang29** [comment]
It worked! Thanks. Now we just reduced our package size by 50% 

App is https://play.google.com/store/apps/details?id=photo.editor.polarr

**Comment by dougdiego** [comment]
Nice App!

Please note, there are newer versions of xwalk if you want it.  You can find them here:
https://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/xwalk/xwalk_core_library/

Just update the dependency:
compile 'org.xwalk:xwalk_core_library:10.39.235.15'

And if you want to get your package size down more, check out this blog post:
https://crosswalk-project.org/blog/crosswalk-lite-10.html

But as far as I can tell, they don't have a maven pom to install it.  You'll have to do it manually.
