### ISSUE TITLE
apk for arm

### ISSUE THREAD

**Issue by interfaith** [dougdiego/CrosswalkDemo#3]
generate apk for arm ?

**Comment by dougdiego** [comment]
You can generate an APK with the command:

./gradlew assembleRelease

It will put the APK at:
app/build/outputs/apk/app-release-unsigned.apk

If you open the APK you'll see the arm binary:
  inflating: lib/armeabi-v7a/libxwalkcore.so
  inflating: lib/x86/libxwalkcore.so

**Comment by interfaith** [comment]
Yes apk files are generated either via android-studio or via the command
line
as you detailed.
However the 'Parsing error ... problem parsing the package' appears when
loading the apk.
The apk is also twice the size !

On Sun, Dec 27, 2015 at 11:23 AM, dougdiego notifications@github.com
wrote:

> You can generate an APK with the command:
> 
> ./gradlew assembleRelease
> 
> It will put the APK at:
> app/build/outputs/apk/app-release-unsigned.apk
> 
> If you open the APK you'll see the arm binary:
> inflating: lib/armeabi-v7a/libxwalkcore.so
> inflating: lib/x86/libxwalkcore.so
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dougdiego/CrosswalkDemo/issues/3#issuecomment-167423305
> .

## 

---

Fight back spam! Download the Blue Frog.
http://www.bluesecurity.com/register/s?user=c3Bvd2FnZTI3NTk%3D
