### ISSUE TITLE
FAILURE: Build failed with an exception on Chromebook using Cloud9IDE

### ISSUE THREAD

**Issue by michaelsboost** [dougdiego/CrosswalkDemo#6]
I'm using the Cloud9IDE on my Chromebook.

I cloned the repo, changed the url in MainActivity.java to my website and ran `./gradlew assembleRelease` as the README.md file stated and got the following error.

> FAILURE: Build failed with an exception.
> - Where:
>   Build file '/home/ubuntu/workspace/CrosswalkDemo/app/build.gradle' line: 17
> - What went wrong:
>   A problem occurred evaluating project ':app'.
>   
>   > SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.
> - Try:
>   Run with --stacktrace option to get the stack trace. Run with --info                                                              or                                                              --debug                                                           option to get more log output.
> 
> BUILD FAILED

**Comment by dougdiego** [comment]
Hi Michael,
I don't have a Chromebook to test this, but it just sounds like you need to set up your build environment.  A google search for your error turned up this: 
http://stackoverflow.com/questions/19794200/gradle-android-and-the-android-home-sdk-location

user u53r solved this problem like:

> I've solved the problem. This works for me:
> 
> In
> 
> /my_current_project/
> I've created a file called local.properties and put inside
> 
> sdk.dir=/my_current_way_to/sdk
> In the console I need to do
> 
> set ANDROID_HOME=/my_current_way_to/sdk
